package com.bigbigdw.manavarasetting.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val color1E1E20 = Color(android.graphics.Color.parseColor("#1E1E20"))
val color121212 = Color(android.graphics.Color.parseColor("#121212"))
val backgroundType3 = Color(android.graphics.Color.parseColor("#26292E"))
val backgroundType4 = Color(android.graphics.Color.parseColor("#0D0E10"))
val color3E424B = Color(android.graphics.Color.parseColor("#3E424B"))
val color621CEF = Color(android.graphics.Color.parseColor("#621CEF"))
val backgroundType9 = Color(android.graphics.Color.parseColor("#0D0D0D"))
val backgroundType10 = Color(android.graphics.Color.parseColor("#404551"))

val colorA7ACB7 = Color(android.graphics.Color.parseColor("#A7ACB7"))
val textColorType2 = Color(android.graphics.Color.parseColor("#898989"))
val colorEDE6FD = Color(android.graphics.Color.parseColor("#EDE6FD"))
val color565c69 = Color(android.graphics.Color.parseColor("#565C69"))
val textColorType5 = Color(android.graphics.Color.parseColor("#844DF3"))
val textColorType6 = Color(android.graphics.Color.parseColor("#F6F6F8"))
val color02BC77 = Color(android.graphics.Color.parseColor("#02BC77"))
val colorFF2366 = Color(android.graphics.Color.parseColor("#FF2366"))
val colorFFFFFF = Color(android.graphics.Color.parseColor("#ffffff"))
val colorE2E3E7 = Color(android.graphics.Color.parseColor("#E2E3E7"))
val colorFDFDFD = Color(android.graphics.Color.parseColor("#FDFDFD"))

val color844DF3 = Color(android.graphics.Color.parseColor("#844DF3"))
val color000000 = Color(android.graphics.Color.parseColor("#000000"))
val colordcdcdd = Color(android.graphics.Color.parseColor("#dcdcdd"))
val color1e4394 = Color(android.graphics.Color.parseColor("#1e4394"))
val color555b68 = Color(android.graphics.Color.parseColor("#555b68"))
val colorf7f7f7 = Color(android.graphics.Color.parseColor("#f7f7f7"))
val color20459e = Color(android.graphics.Color.parseColor("#20459e"))
val color898989 = Color(android.graphics.Color.parseColor("#898989"))
val colorB3000000 = Color(android.graphics.Color.parseColor("#B3000000"))
val color4186e1 = Color(android.graphics.Color.parseColor("#4186e1"))
val colorf6f6f6 = Color(android.graphics.Color.parseColor("#f6f6f6"))


val color52a9ff = Color(android.graphics.Color.parseColor("#52a9ff"))
val color8e8e8e = Color(android.graphics.Color.parseColor("#8e8e8e"))

val color4ad7cf = Color(android.graphics.Color.parseColor("#4ad7cf"))
val color5372de = Color(android.graphics.Color.parseColor("#5372de"))
val color998df9 = Color(android.graphics.Color.parseColor("#998df9"))
val colorea927c = Color(android.graphics.Color.parseColor("#ea927c"))
val colorabd436 = Color(android.graphics.Color.parseColor("#abd436"))
val colorf17fa0 = Color(android.graphics.Color.parseColor("#f17fa0"))
val color21c2ec = Color(android.graphics.Color.parseColor("#21c2ec"))
val color31c3ae = Color(android.graphics.Color.parseColor("#31c3ae"))
val color7c81ff = Color(android.graphics.Color.parseColor("#7c81ff"))
val color64c157 = Color(android.graphics.Color.parseColor("#64c157"))
val colore9e9e9 = Color(android.graphics.Color.parseColor("#e9e9e9"))

val colorf17666 = Color(android.graphics.Color.parseColor("#f17666"))
val color536fd2 = Color(android.graphics.Color.parseColor("#536fd2"))
val color4996e8 = Color(android.graphics.Color.parseColor("#4996e8"))
val colorfdc24e = Color(android.graphics.Color.parseColor("#fdc24e"))
val color80bf78 = Color(android.graphics.Color.parseColor("#80bf78"))
val color91cec7 = Color(android.graphics.Color.parseColor("#91cec7"))
val color79b4f8 = Color(android.graphics.Color.parseColor("#79b4f8"))
val color8aa6bc = Color(android.graphics.Color.parseColor("#8aa6bc"))
val color2ea259 = Color(android.graphics.Color.parseColor("#2ea259"))
val color808cf8 = Color(android.graphics.Color.parseColor("#808cf8"))
val colorffac59 = Color(android.graphics.Color.parseColor("#ffac59"))
val color8f8f8f = Color(android.graphics.Color.parseColor("#8f8f8f"))

